In [8]:
#import libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
import xlsxwriter
import glob

### Renaming Image File

In [9]:
def rename_cardata():
    for count, filename in enumerate (os.listdir("C:/Users/chirag/Downloads/dataset/car")):
        dst = "car1 "+str(count)+".jpg"
        src = "C:/Users/chirag/Downloads/dataset/car"+filename
        dst = "C:/Users/chirag/Downloads/dataset/car"+dst
        os.rename(src,dst)

In [10]:
#renaming images
rename_cardata

<function __main__.rename_cardata()>

### Converting into Gray Scale image and resize it

In [11]:
path = "C:/Users/chirag/Downloads/dataset/car/*.*"
NEW_SIZE = (96,96)
i=0
for file in glob.glob(path):
    img = Image.open(file)
    print("car dataset",i,":")
    print("Original Size:", end="")
    print(img.size,end="")
    imgGray = img.convert('L')
    print("Resize :", end="")
    img1 = imgGray.resize(NEW_SIZE)
    print(img1.size)
    img1.save(f'C:/Users/chirag/Downloads/dataset/GrayScale_Resized/cardata_image_{i}.jpg')
    i+=1

car dataset 0 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 1 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 2 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 3 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 4 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 5 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 6 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 7 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 8 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 9 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 10 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 11 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 12 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 13 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 14 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 15 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 16 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 17 :
Origina

car dataset 141 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 142 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 143 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 144 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 145 :
Original Size:(320, 201)Resize :(96, 96)
car dataset 146 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 147 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 148 :
Original Size:(320, 160)Resize :(96, 96)
car dataset 149 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 150 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 151 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 152 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 153 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 154 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 155 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 156 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 157 :
Original Size:(320, 213)Resize :(96, 9

Original Size:(320, 213)Resize :(96, 96)
car dataset 284 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 285 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 286 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 287 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 288 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 289 :
Original Size:(320, 214)Resize :(96, 96)
car dataset 290 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 291 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 292 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 293 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 294 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 295 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 296 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 297 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 298 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 299 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 300

Original Size:(320, 203)Resize :(96, 96)
car dataset 423 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 424 :
Original Size:(320, 182)Resize :(96, 96)
car dataset 425 :
Original Size:(320, 214)Resize :(96, 96)
car dataset 426 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 427 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 428 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 429 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 430 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 431 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 432 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 433 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 434 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 435 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 436 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 437 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 438 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 439

Original Size:(320, 213)Resize :(96, 96)
car dataset 567 :
Original Size:(320, 182)Resize :(96, 96)
car dataset 568 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 569 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 570 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 571 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 572 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 573 :
Original Size:(320, 187)Resize :(96, 96)
car dataset 574 :
Original Size:(320, 196)Resize :(96, 96)
car dataset 575 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 576 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 577 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 578 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 579 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 580 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 581 :
Original Size:(320, 206)Resize :(96, 96)
car dataset 582 :
Original Size:(320, 209)Resize :(96, 96)
car dataset 583

Original Size:(320, 240)Resize :(96, 96)
car dataset 706 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 707 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 708 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 709 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 710 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 711 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 712 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 713 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 714 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 715 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 716 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 717 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 718 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 719 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 720 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 721 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 722

car dataset 851 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 852 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 853 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 854 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 855 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 856 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 857 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 858 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 859 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 860 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 861 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 862 :
Original Size:(320, 480)Resize :(96, 96)
car dataset 863 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 864 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 865 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 866 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 867 :
Original Size:(320, 240)Resize :(96, 9

Original Size:(320, 480)Resize :(96, 96)
car dataset 995 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 996 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 997 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 998 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 999 :
Original Size:(320, 213)Resize :(96, 96)
car dataset 1000 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 1001 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 1002 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 1003 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 1004 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 1005 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 1006 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 1007 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 1008 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 1009 :
Original Size:(320, 240)Resize :(96, 96)
car dataset 1010 :
Original Size:(320, 240)Resize :(96, 96)
car 

### Extracting Pixel Values nd Strong in a Excel File

In [12]:
workbook = xlsxwriter.Workbook('C:/Users/chirag/Downloads/dataset/data1.xlsx')
worksheet = workbook.add_worksheet()
row=0
column = 0

In [13]:
path = "C:/Users/chirag/Downloads/dataset/car/*.*"
for file in glob.glob(path):
    img = Image.open(file)
    pixels = np.array(img)
    pix = pixels.flatten()
    pix_lst = pix.tolist()
    worksheet.write_row(row,column,pix_lst)
    row+=1
    print(pix)
workbook.close()    

[ 99 110 140 ... 222 218 219]
[255 255 255 ... 255 255 255]
[ 55  28  35 ... 170 167 148]
[106 126 163 ...  54  53  51]
[ 7  7  7 ... 20 27 43]
[214 210 207 ... 115 121 133]
[255 255 255 ... 255 255 255]
[255 255 255 ... 255 255 255]
[255 255 255 ... 255 255 255]
[ 11  15  60 ... 132 133 119]
[255 255 255 ... 255 255 255]
[255 255 255 ... 255 255 255]
[128 128 128 ... 125 125 123]
[255 255 255 ... 255 255 255]
[255 255 255 ... 255 255 255]
[17 17 17 ... 29 42 74]
[255 255 255 ... 255 255 255]
[225 189 167 ... 148 148 146]
[127 151 185 ...  38  36  41]
[214 211 206 ... 110 116 128]
[233 213 188 ... 138 142 145]
[255 255 255 ... 255 255 255]
[179 170 137 ... 132  92  82]
[255 255 255 ... 255 255 255]
[255 255 255 ... 255 255 255]
[255 255 255 ... 255 255 255]
[237 205 190 ... 161 160 158]
[233 213 188 ... 138 142 145]
[255 255 255 ... 255 255 255]
[182 168 133 ... 125  84  62]
[ 61  71 106 ... 107  88 108]
[142 169 199 ...  53  48  54]
[255 255 255 ... 255 255 255]
[171 172 164 ...  83  

[171 173 185 ...  95  85  84]
[255 255 255 ... 255 255 255]
[ 96 102 100 ... 120 121 125]
[ 20  20  20 ... 255 255 255]
[40 37 44 ... 91 92 97]
[146  89  80 ... 125 126 131]
[17 20 13 ... 95 86 71]
[255 255 255 ... 255 255 255]
[193 193 193 ... 233 233 233]
[ 53  63  28 ... 120 106  97]
[40 37 44 ... 91 92 97]
[29 35  9 ... 20 20 18]
[ 35  43  20 ... 117 107 108]
[223 229 243 ... 170 165 161]
[165 183 193 ...  59  55  54]
[199 199 199 ... 105 101 100]
[187 191 203 ... 123 138  43]
[226 235 252 ... 140 129 125]
[239 236 231 ...  79  77  82]
[197 203 215 ... 119 134  49]
[ 34  52  26 ... 160 149 145]
[68 68 68 ...  2  2  2]
[154 156 168 ... 130 120 111]
[255 255 255 ... 255 255 255]
[214 227 243 ...  87  97 107]
[219 218 224 ... 230 224 238]
[ 14   4  12 ... 173 170 163]
[255 255 255 ... 255 255 255]
[218 222 223 ...  53  52  58]
[ 42  52  18 ... 128 114 105]
[197 194 185 ...  82  65  75]
[25  9  9 ... 73 73 73]
[213 216 221 ... 136 133 128]
[27 16 14 ... 79 79 81]
[ 49  67  91 ... 151 1

[250 223 194 ... 255 255 255]
[248 248 248 ... 207 200 192]
[255 255 255 ... 255 255 255]
[145 117 106 ...  29  11   9]
[255 255 255 ... 255 255 255]
[255 252 255 ... 254 226 222]
[255 255 255 ... 255 255 255]
[255 255 255 ... 255 255 255]
[188 198 208 ... 255 247 254]
[255 252 255 ... 241 231 219]
[255 255 255 ... 255 255 255]
[255 209 211 ... 253 255 252]
[255 255 255 ... 255 255 255]
[15  6 27 ... 57 38 40]
[ 88  61  42 ... 193 183 184]
[121 137 150 ... 129 123 137]
[ 12   0  22 ... 196 152 153]
[  3   3   3 ... 238 228 227]
[  8   7   5 ... 179 175 176]
[ 67  49  49 ... 227 225 226]
[78 53 57 ... 78 78 78]
[ 21  20  25 ... 249 253 255]
[ 39  16  24 ... 247 254 255]
[254 250 239 ...   6  11  14]
[251 243 232 ... 201 194 176]
[243 224 184 ... 253 251 239]
[ 25  16  19 ... 130 134 135]
[ 48  17  14 ... 208 217 214]
[172 158 145 ... 108 112 124]
[237 232 228 ... 183 121 134]
[107  85  71 ...  31  30  36]
[243 224 194 ... 190 188 176]
[183 204 189 ...   0   8  46]
[215 199 173 ...  40  

[  9  22  38 ... 189 193 194]
[73 63 54 ... 79 67 55]
[28 11 29 ... 32 34 46]
[255 255 255 ... 255 255 255]
[191 218 203 ...  96  97 101]
[255 255 255 ... 255 255 255]
[ 40  38  39 ... 151 138 119]
[243 244 246 ...   4  10  10]
[ 78  80  75 ... 148 148 148]
[156 182 205 ...  88  88  86]
[225 234 241 ...  95  99 110]
[ 97 115 115 ...  88  98 107]
[31 30 25 ... 11 15 40]
[255 255 255 ... 255 255 255]
[ 91  71  46 ... 253 253 253]
[26 29 34 ... 87 87 89]
[103 122 154 ... 204 201 196]
[255 255 255 ... 255 255 255]
[255 255 255 ... 255 255 255]
[174 143  89 ... 230 225 221]
[76 76 76 ... 27 27 27]
[255 255 255 ... 255 255 255]
[ 82  66  43 ... 187 187 187]
[255 255 255 ... 255 255 255]
[152 183 204 ...  89  89  87]
[53 62 71 ...  0  0  0]
[ 83  66  46 ... 185 185 185]
[240 239 235 ... 155 152 147]
[255 255 255 ... 255 255 255]
[  9  10  12 ... 221 220 216]
[255 255 255 ... 255 255 255]
[ 83  66  46 ... 185 185 185]
[ 19  18  23 ... 183 170 154]
[255 255 255 ... 255 255 255]
[163 163 153 ...

[255 255 255 ... 255 255 255]
[255 255 255 ... 255 255 255]
[145 149 152 ... 154 155 159]
[214 216 211 ...  29  29  31]
[255 255 255 ... 255 255 255]
[171 171 171 ...  65  65  65]
[255 255 255 ... 255 255 255]
[ 8  4  5 ... 92 69 35]
[255 255 255 ... 255 255 255]
[255 255 255 ... 255 255 255]
[255 255 255 ... 255 255 255]
[255 255 255 ... 255 255 255]
[255 255 255 ... 255 255 255]
[ 29  52  68 ... 138 139 134]
[255 255 255 ... 255 255 255]
[255 255 255 ... 255 255 255]


In [ ]:
df1 = pd.read_excel('C:/Users/chirag/Downloads/dataset/data1.xlsx', header=None)
col = [*range(0,9216, 1)]
features = ['X'+str(a) for a in col]
df1 = df1.set_axis(features,axis=1, inplace=False)
df1.loc[:,'y']=0
df1.head()

In [ ]:
df1.shape

### EDA

In [ ]:
print("car:",len(df1[df1['y']==0]))